[mypy]
disallow_untyped_defs = False
disable_error_code = arg-type, assignment, operator, union-attr
ignore_missing_imports = True
show_error_codes = True
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
