# -*- coding: utf-8 -*-
"""
Created on Mon May 30 18:02:45 2022

@author: pahar
"""

print ("FINANCIAL INPUTS")
print ('Please input the financial constants required for the analysis:')
print ('')
current_rate= float(input ('Exchange rate [LBP/$]: '))
discount_rate=float(input("Discount rate [0-1]:"))
general_om=float(input("General overall O&M [$ p.a]:"))
print("")
print("MISCELLANEOUS INPUTS:")
print("")
m_cost=float(input("Cost [$/kW]:"))
print("")
print("BALANCE OF SYSTEM INPUTS:")
print("")
bos_cost=float(input("BOS cost [$/kW]:"))
bos_cost_decrease=float(input("BOS yearly cost decrease [% p.a]:"))
print("")
print("Please input the household connection costs:")
print("")
connection_cost=float(input("Household connection cost [$/household]:"))
inverter_cost=float(input("Inverter cost [$/kW]:"))
inverter_cost_decrease=float(input("Yearly inverter cost decrease [$/kW]:"))
inverter_lifetime=int(input("Inverter lifetime [years]:"))
size_increment=float(input("Inverter size increment [kW]:"))
print("")
b=str(input("Is Kerosene used as backup in the study? [Y for YES, N for NO]:"))
if b in ['y','Y','Yes','YES']:
    ker_cost=float(input("Kerosene cost [$/hour]:"))
else:
    print("Kerosene will not be included in the study")
    ker_cost=0
print("")
print ("Diesel generator GRID data:")
print("")
mdemand=float(input('Monthly average demand Household [kWh/month]:'))
cost_edl=5 #initial value for nothing
category=1
subscription_cost=1

#  # EDL GRID COSTS: This is the cost of the electricity when generated by EDL and this is separated in increments
if mdemand<100: #(daily demand EDL * 30 days, the bill will have cost edl associated )
    cost_edl=35/current_rate
    category=1
elif mdemand>=101 and mdemand<300:
    cost_edl=55/current_rate
    category=2
elif mdemand>=301 and mdemand<400:
    cost_edl=80/current_rate
    category=3
elif mdemand>=401 and mdemand<500:
    cost_edl=120/current_rate
    category=4
    
else:
    cost_edl=200/current_rate
    category=5
print("*******************************************************************************")
print("******EDL Electricity tariff for threshold",category,"=",cost_edl,"$/kWh******")        
print("*******************************************************************************")
print("")
print("****************************")
print ("Diesel generator GRID data:")
print("****************************")
print("")
print("DIESEL FUEL INPUTS:")# here it should be based on the exchange rate
print("")
d_cost=float(input("Diesel fuel cost per litre [$/L]:"))
d_cost_decrease=float(input("Yearly Diesel fuel cost [% p.a] (Negative if price increased over the last year):"))
capacity_needed= float(input ('Household Amperage needed [A]:'))
cost_DG= float(input("Current community Diesel Generator tariff [$/kWh]:"))
print("")
# grid DG (2)
subscription_cost_yearly=0
for i in range (0,12):
    if capacity_needed <=1.1: #max capacity needed at any time of the day is 5A
        subscription_cost=(50000/current_rate)
    else: #max capacity needed at any time of the day is 10A
        subscription_cost=(150000/current_rate) # [$ p.a] double check that   
    subscription_cost_yearly=subscription_cost_yearly+subscription_cost

print("")
print ("Diesel Generator yearly subscription for",capacity_needed,"=",subscription_cost,"$/year") 
print("")

c=str(input("Is the analysis done for a household or an array of houses? [H for household and A for array]:"))
if c in ['h','H','Household','household']:
    extension_cost=0
    infrastructure_cost=0
    print ("No extension cost needed")
    print ("No Infrastructure cost needed too")
else:
    print ("Taking the extension and infrastructure cost for the expension of our system is essential!")
    print ("")
    extension_cost=float(input("Diesel generator extension cost [$/km]:"))
    infrastructure_cost=float(input("Diesel generator infrastructure cost [$]:"))
