# -*- coding: utf-8 -*-
"""
Created on Mon May 30 13:45:21 2022

@author: Paul Harfouche
"""
  
current_rate= int(input ('Exchange rate [LBP/$]: '))
capacity_needed= int(input ('Household Amperage needed [A]:'))
mdemand=int(input('Monthly average demand Household [kWh/month]:'))
cost=5 #initial value for nothing
category=1
subscription_cost=1

#  # EDL GRID COSTS: This is the cost of the electricity when generated by EDL and this is separated in increments
if mdemand<100:
    cost=35/current_rate
    category=1
elif mdemand>=101 and mdemand<300:
    cost=55/current_rate
    category=2
elif mdemand>=301 and mdemand<400:
    cost=80/current_rate
    category=3
elif mdemand>=401 and mdemand<500:
    cost=120/current_rate
    category=4
    
else:
    cost=200/current_rate
    category=5

print ("EDL Electricity tariff for threshold",category,"=",cost,"$/kWh")        

cost_DG= 0.407299 # [$/kWh]
extension_cost=0 # [$/km]
infrastructure_cost=0 # [$]

# grid DG (2)
if capacity_needed <=5:
    subscription_cost=(50000/current_rate)*12
elif capacity_needed>5 and capacity_needed<=15:
    subscription_cost=(150000/current_rate)*12 # [$ p.a] double check that   
else:
    subscription_cost= (250000/current_rate)*12 # [$ p.a] double check that

print ("Diesel Generator yearly subscription for",capacity_needed,"=",subscription_cost,"$/year") 