# -*- coding: utf-8 -*-
"""
Created on Tue Jun  7 17:46:49 2022

@author: pahar
"""

#SAMPLE OF CODE FOR DYNAMIC PRICING

current_rate=25000
max_daily_capacity_needed=1.2
EDL_monthly_demand=1

# EDL GRID COSTS: This is the cost of the electricity when generated by EDL and this is separated in increments

#if EDL ON THEN WHEN EDL IS WORKING 
if EDL_monthly_demand<100: #(daily demand EDL * 30 days, the bill will have cost edl associated )
    cost_edl=35/current_rate
    category=1 #CURRENTLY EVERYONE IS IN CATEGORY 1 BECAUSE 2 HOURS MAX A DAY AND NOT AT PEAK TIME - MAX KWH MONTHLY=40kWh
elif EDL_monthly_demand>=101 and EDL_monthly_demand<300:
    cost_edl=55/current_rate
    category=2
elif EDL_monthly_demand>=301 and EDL_monthly_demand<400:
    cost_edl=80/current_rate
    category=3
elif EDL_monthly_demand>=401 and EDL_monthly_demand<500:
    cost_edl=120/current_rate
    category=4
else:
    cost_edl=200/current_rate
    category=5
    
# DIESEL GENERATOR DYNAMIC PRICING
subscription_cost_yearly=0
for i in range (0,12):
    if max_daily_capacity_needed <=1.1: #max capacity needed at any time of the day is 5A
        subscription_cost=(50000/current_rate)
    else: #max capacity needed at any time of the day is 10A
        subscription_cost=(150000/current_rate) # [$ p.a] double check that   
    subscription_cost_yearly=subscription_cost_yearly+subscription_cost
