name: Open Journals PDF Generator

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v.1.0
